### ISSUE TITLE
"list group aliases" return "robot is not defined" 

### ISSUE THREAD

**Issue by vspiewak** [cycomachead/hubot-group-alias#12]
I use hubot-auth and hubot-group-alias with ``HUBOT_GROUP_ALIAS='DYNAMIC'``.

The command 'list group alias' return nothing, and hubot log contains:

````
[Mon Apr 25 2016 18:24:53 GMT+0200 (CEST)] ERROR ReferenceError: robot is not defined
  at getGroupsList (/opt/hubot/node_modules/hubot-group-alias/src/alias.coffee:66:5, <js>:62:15)
  at TextListener.callback (/opt/hubot/node_modules/hubot-group-alias/src/alias.coffee:120:14, <js>:135:31)
  at executeListener (/opt/hubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/opt/hubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /opt/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/opt/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/opt/hubot/node_modules/async/lib/async.js:268:15)
  at /opt/hubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at nextTickCallbackWith0Args (node.js:453:9)
  at process._tickCallback (node.js:382:13)
````

Maybe I'm missing something ?

**Comment by cycomachead** [comment]
Weird, it works on my Hubot instance. However, after re-reading the code, I'm actually not sure that it _should_ be working. I'll post a fix in a few.

**Comment by cycomachead** [comment]
Try downloading the newest version, and let me know if that fixes things.

**Comment by vspiewak** [comment]
2.1.3 fix the issue :)

Best Regards
